#ifndef _NURCOMMANDS_H_
#define _NURCOMMANDS_H_

/** @addtogroup NURPROTO
 *  @{
 */

/**
 * NUR module basic commands
 */
enum {
	NUR_BASIC_BASE = 1,
	NUR_CMD_PING = NUR_BASIC_BASE,
	NUR_CMD_ACK,
	NUR_CMD_RESET,
	NUR_CMD_GETMODE,
	NUR_CMD_CLEARIDBUF,
	NUR_CMD_GETIDBUF,
	NUR_CMD_GETMETABUF,
	NUR_CMD_GETSYSTEM,
  	NUR_CMD_GETREADERINFO,
  	NUR_CMD_MCUARCH,
  	NUR_CMD_DEVCAPS,
  	NUR_CMD_VERSIONEX,
	NUR_CMD_BEEP,
	NUR_CMD_STOPALLCONT,
	NUR_CMD_CONFIGGPIO, 
	NUR_CMD_GETGPIO, 
	NUR_CMD_SETGPIO, 
	NUR_CMD_SENSORS, 
	NUR_CMD_FACTORYRESET, 
	NUR_CMD_RESTART,
	NUR_CMD_GETETHCONFIG,
	NUR_CMD_SETETHCONFIG,
	NUR_CMD_TITLE_SET,
	NUR_CMD_TITLE_GET,		
	NUR_CMD_GETFWINFO = 30,	
	NUR_BASIC_LAST
};
#define NUR_BASIC_CMD_RANGE(_cmd)   (((_cmd)>=NUR_BASIC_BASE)&&((_cmd)<NUR_BASIC_LAST))

/**
 * NUR module control commands 
 */
enum {
	NUR_CTL_BASE = 0x20,	
	NUR_CMD_SETBDR = NUR_CTL_BASE,
	NUR_CMD_ANTIDTRANSLATION,	// WAS CMD_RESERVED3, IN USE SINCE 4.9-L
	NUR_CMD_LOADSETUP2,
	NUR_CMD_INVREADCONFIG,
	NUR_CMD_GETREGIONINFO,
	NUR_CMD_ANTENNAMAP,		// WAS CMD_RESERVED5, IN USE SINCE 4.9-H
	NUR_CMD_ANTPOWER,		// WAS CMD_RESERVED4, IN USE SINCE 4.9-H	
	NUR_CMD_ANTENNA,		// No used atm
	NUR_CMD_STORESETUP,
	NUR_CMD_CUSTOMHOP,	
	NUR_CMD_CUSTOMHOP_EX,	// 0x2A
	NUR_CMD_DIAG,
	NUR_CTL_LAST // Max 0x2F
};
#define NUR_CTL_CMD_RANGE(_cmd)	(((_cmd)>=NUR_CTL_BASE)&&((_cmd)<NUR_CTL_LAST))

/**
 * NUR module UHF G2 commands
 */
enum {
	NUR_G2_BASE = 0x30,
	NUR_CMD_SCANSINGLE = NUR_G2_BASE,
	NUR_CMD_INVENTORY,
	NUR_CMD_INVENTORYSEL,
	NUR_CMD_READ,
	NUR_CMD_WRITE,
	NUR_CMD_BLWRITE,
	NUR_CMD_LOCK,
	NUR_CMD_KILL,
	NUR_CMD_TRACETAG,
	NUR_CMD_INVENTORYSTREAM,
	NUR_CMD_RESETTARGET,
	NUR_CMD_INVENTORYEX,
	NUR_CMD_CUSTREAD,
	NUR_CMD_CUSTWRITE,
	NUR_CMD_CUSTBLWRITE,
	NUR_CMD_CUSTOMEXCHANGE,
	NUR_CMD_BLKERASE,
	NUR_CMD_INVENTORYREAD,
	NUR_CMD_BLWRITE_EX,
	NUR_CMD_EPCENUM,
	NUR_CMD_PERMALOCK,
	NUR_CMD_TAGTRACKING_STREAM, // Internal stream mode used by NURAPI TagTracking
	NUR_CMD_GEN2V2,		// Operates on sub-commands and their structures.
	NUR_G2_LAST
};
#define NUR_G2_CMD_RANGE(_cmd) (((_cmd)>=NUR_G2_BASE)&&((_cmd)<NUR_G2_LAST))

/*
  Proprietary. Todo:
  - NXP
  - Impinj's Monza4
  - NXP new commands (after G2M)  
*/
/**
 * NUR module proprietary extensions commands
 */
enum {
	NUR_PROPR_BASE = 0x50,
	NUR_NXPCMD_RDPROTECT = NUR_PROPR_BASE,
	NUR_NXPCMD_EAS,
	NUR_NXPCMD_EASALARM,
	NUR_MZ4CMD_QT,
	NUR_NXPCMD_EASALARMSTREAM,
	NUR_CMD_ACC_EXT,
	NUR_EXT, // AR
	NUR_PROPR_LAST
};
#define NUR_PROPR_CMD_RANGE(_cmd)	    (((_cmd)>=NUR_PROPR_BASE)&&((_cmd)<NUR_PROPR_LAST))

/**
 * NUR module test commands
 */
enum {
	NUR_TEST_BASE = 0x60,
	NUR_CMD_GETREFPOWER = NUR_TEST_BASE,
	NUR_CMD_CONTCARR,
	NUR_CMD_CARRIER,
	NUR_CMD_SCANCHANNELS,
	NUR_CMD_RFSETTINGS,
	NUR_CMD_RFRESERVED1,
	NUR_CMD_TUNEANTENNA,	/* Current tune command. */
	NUR_CMD_GETREFPOWEREX,
	NUR_CMD_GRIDANTENNA_DEPRECATED,	/* Deprecated */
	NUR_CMD_NOTCHFILTER, // ??
	NUR_CMD_SETCHANNEL,
	NUR_CMD_AUTOTUNE_TESTING_NOTINUSE,	 /* Maybe reused in future for something else */
	NUR_CMD_ANTPOWEREX_TESTING_NOTINUSE, /* Maybe reused in future for something else */
	NUR_CMD_MEASURE_RAW_BLF,
	NUR_TEST_LAST
};
#define NUR_TEST_CMD_RANGE(_cmd)	   (((_cmd)>=NUR_TEST_BASE)&&((_cmd)<NUR_TEST_LAST))

/**
 * NUR module bootloader commands
 */
enum {
	NUR_BOOT_BASE = 0x70,
	NUR_CMD_UNLOCKALL = NUR_BOOT_BASE,
	NUR_CMD_PAGEWRITE,
	NUR_CMD_PAGEREAD,
	NUR_CMD_ENTERBOOT,
	NUR_CMD_APPVALIDATE,
	NUR_CMD_QUERYCRC,
	NUR_CMD_PRODUCTION_CFG,
	NUR_CMD_BLVALIDATE,
	NUR_CMD_CRYPTOBYPASS,
	NUR_CMD_SCRATCHDATA,	
	NUR_BOOT_LAST
};
#define NUR_BOOT_CMD_RANGE(_cmd)   (((_cmd)>=NUR_BOOT_BASE)&&((_cmd)<NUR_BOOT_LAST))

/**
 * NUR module notifications
 */
enum {
	NUR_NOTIFY_BOOT = 0x80,
	NUR_NOTIFY_IOCHANGE,
	NUR_NOTIFY_INVENTORY,
	NUR_NOTIFY_TT_INVENTORY,
	NUR_NOTIFY_TRACETAG,
	NUR_NOTIFY_TRIGGERREAD,
	NUR_NOTIFY_HOPEVENT,
	NUR_NOTIFY_DEBUGMSG,
	NUR_NOTIFY_INVENTORYEX,
	NUR_NOTIFY_NXPALARM,
	NUR_NOTIFY_EPCENUM,
	NUR_NOTIFY_EXTIN,
	NUR_NOTIFY_GENERAL,
	NUR_NOTIFY_AUTOTUNE,
	NUR_NOTIFY_WLAN_SEARCH,
	NUR_NOTIFY_DIAG,
	NUR_NOTIFY_BLE_ACCESSORY,
	NUR_NOTIFY_LAST
};

/**
 * NUR module register commands 
 */
enum {
	NUR_REG_BASE = 0x90,
	NUR_CMD_READREG = NUR_REG_BASE,
	NUR_CMD_WRITEREG,
	NUR_CMD_MAKEPERMANENT,
	NUR_CMD_WRITELONG,
	NUR_CMD_REGDUMP,
	NUR_CMD_GENSETUP,
	NUR_CMD_READCONT,
	NUR_CMD_READALL,
	NUR_REG_LAST
};

/*
  Standalone and commands for ethernet Sampo
*/
enum {
	NUR_ETH_BASE = 0xA0,
	NUR_CMD_STANDALONE_GET_1 = NUR_ETH_BASE,
	NUR_CMD_STANDALONE_SET_1,
	NUR_CMD_STANDALONE_GET_2,
	NUR_CMD_STANDALONE_SET_2,	
	NUR_CMD_EXTIO,
	NUR_CMD_ETHCLOCK,
	NUR_CMD_ALLOW_NOTIFY,
	NUR_CMD_GET_HCR,
	NUR_CMD_GET_BUFFEREDDATA,
	NUR_CMD_ACK_BUFFEREDDATA,
	NUR_ETH_LAST	
};

/*
  NASS Commands
*/
enum {
	NASS_BASE = 0xB0,
	NASS_DATA = NASS_BASE,
	NASS_LAST	
};

#define NUR_REG_CMD_RANGE(_cmd)	(((_cmd)>=NUR_REG_BASE)&&((_cmd)<NUR_REG_LAST))

/*
	Gen2 version 2 sub-command values.
	See XNUR3 : app/inc/gen2v2.h for more. These are supported for now.
*/

#define GEN2_V2CMD_AUTH			0x00D5
#define GEN2_V2CMD_UNTRACE		0xE200
#define GEN2_V2CMD_RDBUF		0x00D2

/* NUR_CMD_DIAG sub commands */
enum {
	NUR_CMD_DIAG_GETREPORT = 1,
	NUR_CMD_DIAG_CFG,
	NUR_CMD_DIAG_LAST
};

/** @} */ // end of NURPROTO

#endif
